# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-24 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220424_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uid', models.TextField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
